# Site settings
title: Access Land
email: us@accessland.org
description: "Keep data about public land available and open to everybody."
baseurl: ""
url: "http://accessland.org"

exclude: [vendor]

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: :compressed